language: node_js
node_js:
  - "6"
sudo: false
cache:
  directories:
    - "node_modules"

script:
  # run tests
  - npm run test
  # run build
  - npm run build
  # deploy with travis
  - bash ./.travis-deploy.sh